<?php

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

$GLOBALS['wgce_config_backend'] = [];
$GLOBALS['wgce_wireguard_mutations'] = [];

function wgce_config_reset(mixed $value): void
{
    $GLOBALS['wgce_config_backend'] = [
        'values' => [
            'installedpackages/wgclientexport/config' => [0 => $value],
            'installedpackages/wgclientexport/config/0' => $value,
        ],
        'events' => [],
    ];
    $GLOBALS['wgce_wireguard_mutations'] = [];
}

function config_get_path(string $path, mixed $default = null): mixed
{
    $GLOBALS['wgce_config_backend']['events'][] = ['get', $path];
    return array_key_exists($path, $GLOBALS['wgce_config_backend']['values'])
        ? $GLOBALS['wgce_config_backend']['values'][$path] : $default;
}

function config_set_path(string $path, mixed $value): mixed
{
    $GLOBALS['wgce_config_backend']['events'][] = ['set', $path, $value];
    $GLOBALS['wgce_config_backend']['values'][$path] = $value;
    if ($path === 'installedpackages/wgclientexport/config/0') {
        $parent = $GLOBALS['wgce_config_backend']['values']['installedpackages/wgclientexport/config'] ?? [];
        $parent = is_array($parent) ? $parent : [];
        $parent[0] = $value;
        $GLOBALS['wgce_config_backend']['values']['installedpackages/wgclientexport/config'] = $parent;
    }
    return null;
}

function write_config(string $message): mixed
{
    $GLOBALS['wgce_config_backend']['events'][] = ['write', $message];
    return null;
}

function wg_do_peer_post(array $payload): array
{
    $GLOBALS['wgce_wireguard_mutations'][] = ['create_peer', $payload];
    return [];
}

function wg_tunnel_sync(array $tunnels, bool $force = true, bool $reload = true): array
{
    $GLOBALS['wgce_wireguard_mutations'][] = ['sync_tunnel', $tunnels, $force, $reload];
    return [];
}

function wg_delete_peer(int $index): array
{
    $GLOBALS['wgce_wireguard_mutations'][] = ['delete_peer', $index];
    return [];
}

require_once wgce_project_root() . '/files/usr/local/pkg/wgclientexport/bootstrap.inc';

function wgce_config_fixture(): array
{
    return [
        'schema_version' => '1',
        'tunnels' => ['item' => [[
            'tunnel_id' => 'tun_wg0',
            'enabled' => 'yes',
            'client_pool_ipv4' => '10.77.0.0/24',
            'endpoint_host' => 'vpn.example.test',
            'endpoint_port' => '51820',
            'dns_ipv4' => ['item' => ['192.0.2.53']],
            'persistent_keepalive' => '25',
            'local_routes_ipv4' => ['item' => ['192.0.2.0/24']],
            'reservations_ipv4' => ['item' => ['10.77.0.9']],
        ]]],
    ];
}

function wgce_config_events_of_type(string $type): array
{
    return array_values(array_filter(
        $GLOBALS['wgce_config_backend']['events'],
        static fn(array $event): bool => $event[0] === $type
    ));
}

wgce_test('pfSense package settings use the indexed config row path', static function (): void {
    wgce_config_reset(wgce_config_fixture());

    $settings = wgclientexport_get_settings();

    wgce_assert_same('installedpackages/wgclientexport/config/0', WGCLIENTEXPORT_CONFIG_PATH);
    wgce_assert_same(wgce_config_fixture(), $settings);
    wgce_assert_same(
        [['get', 'installedpackages/wgclientexport/config/0']],
        $GLOBALS['wgce_config_backend']['events']
    );
});

wgce_test('install repairs scalar and malformed empty package rows with secret-free defaults', static function (): void {
    $malformedStates = [
        'scalar generated by the old unindexed path' => '1',
        'empty array' => [],
        'non-array tunnels node' => ['schema_version' => '1', 'tunnels' => '1'],
    ];

    foreach ($malformedStates as $case => $malformed) {
        wgce_config_reset($malformed);

        $result = wgclientexport_install();

        wgce_assert_same([], $result['input_errors'], 'Unexpected repair error for ' . $case);
        wgce_assert_true($result['changes'], 'Malformed state was not repaired for ' . $case);
        wgce_assert_same(wgclientexport_default_settings(), $result['result']);
        $sets = wgce_config_events_of_type('set');
        wgce_assert_same(1, count($sets), 'Repair did not perform exactly one set for ' . $case);
        wgce_assert_same('installedpackages/wgclientexport/config/0', $sets[0][1]);
        wgce_assert_same(wgclientexport_default_settings(), $sets[0][2]);
        wgce_assert_same(
            [0 => wgclientexport_default_settings()],
            $GLOBALS['wgce_config_backend']['values']['installedpackages/wgclientexport/config']
        );
        wgce_assert_same(1, count(wgce_config_events_of_type('write')));
        wgce_assert_false(wgclientexport_contains_secret_field($sets[0][2]));
        wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
    }
});

wgce_test('pfSense empty scalar tunnel storage is canonical and install is idempotent', static function (): void {
    wgce_config_reset(['schema_version' => '1', 'tunnels' => '']);

    $settings = wgclientexport_get_settings();
    $result = wgclientexport_install();

    wgce_assert_same(wgclientexport_default_settings(), $settings);
    wgce_assert_same([], $result['input_errors']);
    wgce_assert_false($result['changes']);
    wgce_assert_same(wgclientexport_default_settings(), $result['result']);
    wgce_assert_same([], wgce_config_events_of_type('set'));
    wgce_assert_same([], wgce_config_events_of_type('write'));
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('a single associative pfSense item normalizes without rewriting', static function (): void {
    $stored = wgce_config_fixture();
    $stored['tunnels']['item'] = $stored['tunnels']['item'][0];
    wgce_config_reset($stored);

    $settings = wgclientexport_get_settings();
    $result = wgclientexport_install();

    wgce_assert_same(wgce_config_fixture(), $settings);
    wgce_assert_same([], $result['input_errors']);
    wgce_assert_false($result['changes']);
    wgce_assert_same(wgce_config_fixture(), $result['result']);
    wgce_assert_same([], wgce_config_events_of_type('set'));
    wgce_assert_same([], wgce_config_events_of_type('write'));
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('install strips secret fields from supported stored settings', static function (): void {
    $unsafe = wgce_config_fixture();
    $unsafe['tunnels']['item'][0]['metadata'] = [
        'client_private_key' => wgce_synthetic_key('S'),
    ];
    wgce_config_reset($unsafe);

    $result = wgclientexport_install();

    wgce_assert_same([], $result['input_errors']);
    wgce_assert_true($result['changes']);
    wgce_assert_same(wgce_config_fixture(), $result['result']);
    wgce_assert_false(wgclientexport_contains_secret_field($result['result']));
    wgce_assert_same(
        wgce_config_fixture(),
        $GLOBALS['wgce_config_backend']['values']['installedpackages/wgclientexport/config/0']
    );
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('future settings schema fails closed for install and save', static function (): void {
    $future = wgce_config_fixture();
    $future['schema_version'] = '2';
    $future['future_field'] = ['preserve' => 'yes'];
    wgce_config_reset($future);

    $error = wgce_assert_throws(
        static fn(): array => wgclientexport_install(),
        RuntimeException::class
    );
    wgce_assert_not_contains('2', $error->getMessage());
    $save = wgclientexport_save_settings(wgce_config_fixture()['tunnels']['item'][0]);

    wgce_assert_false($save['saved']);
    wgce_assert_false($save['changes']);
    wgce_assert_true($save['input_errors'] !== []);
    wgce_assert_same([], wgce_config_events_of_type('set'));
    wgce_assert_same([], wgce_config_events_of_type('write'));
    wgce_assert_same(
        $future,
        $GLOBALS['wgce_config_backend']['values']['installedpackages/wgclientexport/config/0']
    );
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('install preserves an already valid settings row without writing or mutating WireGuard', static function (): void {
    $valid = wgce_config_fixture();
    wgce_config_reset($valid);

    $result = wgclientexport_install();

    wgce_assert_same([], $result['input_errors']);
    wgce_assert_false($result['changes']);
    wgce_assert_same($valid, $result['result']);
    wgce_assert_same([], wgce_config_events_of_type('set'));
    wgce_assert_same([], wgce_config_events_of_type('write'));
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('settings save persists only to the indexed package row', static function (): void {
    wgce_config_reset(wgclientexport_default_settings());
    $input = wgce_config_fixture()['tunnels']['item'][0];

    $result = wgclientexport_save_settings($input);

    wgce_assert_true($result['saved']);
    wgce_assert_true($result['changes']);
    $sets = wgce_config_events_of_type('set');
    wgce_assert_same(1, count($sets));
    wgce_assert_same('installedpackages/wgclientexport/config/0', $sets[0][1]);
    foreach ($GLOBALS['wgce_config_backend']['events'] as $event) {
        if ($event[0] === 'get' || $event[0] === 'set') {
            wgce_assert_same('installedpackages/wgclientexport/config/0', $event[1]);
        }
    }
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('secret-bearing settings are rejected before any configuration access', static function (): void {
    wgce_config_reset(wgclientexport_default_settings());
    $input = wgce_config_fixture()['tunnels']['item'][0];
    $input['metadata'] = ['client_private_key' => wgce_synthetic_key('C')];
    $GLOBALS['wgce_config_backend']['events'] = [];

    $result = wgclientexport_save_settings($input);

    wgce_assert_false($result['saved']);
    wgce_assert_false($result['changes']);
    wgce_assert_same(null, $result['result']);
    wgce_assert_true($result['input_errors'] !== []);
    wgce_assert_same([], $GLOBALS['wgce_config_backend']['events']);
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('safe suggestions derive tunnel, DDNS, DNS and local route defaults without persistence', static function (): void {
    wgce_config_reset(wgclientexport_default_settings());
    $GLOBALS['wgce_config_backend']['events'] = [];
    $tunnel = [
        'name' => 'tun_wg0',
        'listen_port' => 51820,
        'addresses' => ['row' => [
            ['address' => '10.66.66.1', 'mask' => '24'],
            ['address' => '2001:db8::1', 'mask' => '64'],
        ]],
    ];
    $context = [
        'dns_servers' => [
            '8.8.8.8',
            ['item' => ['1.1.1.1', '8.8.8.8', '192.168.1.1', '127.0.0.1']],
            'invalid',
        ],
        'ddns_records' => [
            ['host' => 'VPN.Example.Test'],
            ['hostname' => 'vpn.example.test'],
            ['host' => 'disabled.example.test', 'enable' => true],
        ],
        'wan_ipv4' => '93.184.216.34',
        'local_networks' => [
            ['address' => '192.168.1.118', 'mask' => '24'],
            '172.16.8.4/23',
            '192.168.1.0/24',
            '0.0.0.0/0',
            'not-a-route',
        ],
    ];

    $suggested = wgclientexport_suggest_tunnel_settings($tunnel, $context);

    wgce_assert_same('tun_wg0', $suggested['tunnel_id']);
    wgce_assert_same('yes', $suggested['enabled']);
    wgce_assert_same('10.66.66.0/24', $suggested['client_pool_ipv4']);
    wgce_assert_same('vpn.example.test', $suggested['endpoint_host']);
    wgce_assert_same('51820', $suggested['endpoint_port']);
    wgce_assert_same(
        ['item' => ['8.8.8.8', '1.1.1.1', '192.168.1.1']],
        $suggested['dns_ipv4']
    );
    wgce_assert_same('25', $suggested['persistent_keepalive']);
    wgce_assert_same(
        ['item' => ['192.168.1.0/24', '172.16.8.0/23']],
        $suggested['local_routes_ipv4']
    );
    wgce_assert_same(['item' => []], $suggested['reservations_ipv4']);
    wgce_assert_false(wgclientexport_contains_secret_field($suggested));
    wgce_assert_same([], $GLOBALS['wgce_config_backend']['events']);
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test('private WAN does not become a client endpoint', static function (): void {
    $suggested = wgclientexport_suggest_tunnel_settings(
        [
            'name' => 'tun_wg0',
            'listenport' => '51820',
            'addresses' => ['row' => ['address' => '10.77.0.1', 'mask' => '24']],
        ],
        ['wan_ipv4' => '192.168.1.118']
    );

    wgce_assert_same('', $suggested['endpoint_host']);
    wgce_assert_same('10.77.0.0/24', $suggested['client_pool_ipv4']);
    wgce_assert_same('51820', $suggested['endpoint_port']);
});

wgce_test('a unique DDNS hostname has priority over a public WAN address', static function (): void {
    $host = wgclientexport_suggest_endpoint_host(
        [['host' => 'wg.example.test']],
        '93.184.216.34'
    );

    wgce_assert_same('wg.example.test', $host);
});

wgce_test('a genuinely public WAN address is suggested when DDNS is not unique', static function (): void {
    $public = wgclientexport_suggest_endpoint_host([], '93.184.216.34');
    $ambiguous = wgclientexport_suggest_endpoint_host(
        [['host' => 'first.example.test'], ['host' => 'second.example.test']],
        '93.184.216.34'
    );

    wgce_assert_same('93.184.216.34', $public);
    wgce_assert_same('93.184.216.34', $ambiguous);
    foreach ([
        '0.0.0.1',
        '10.1.2.3',
        '100.64.0.1',
        '127.0.0.1',
        '169.254.1.1',
        '172.16.0.1',
        '192.0.2.1',
        '192.168.1.118',
        '198.18.0.1',
        '198.51.100.1',
        '203.0.113.10',
        '224.0.0.1',
        '240.0.0.1',
    ] as $nonPublic) {
        wgce_assert_same('', wgclientexport_suggest_endpoint_host([], $nonPublic));
    }
});

wgce_test('DNS suggestions are deduplicated, IPv4-only, usable and bounded', static function (): void {
    $dns = wgclientexport_suggest_dns_ipv4([
        '127.0.0.1', '8.8.8.8', '8.8.8.8', '::1', '169.254.1.1',
        '1.1.1.1', '192.168.1.1', '9.9.9.9', '4.2.2.2',
    ]);

    wgce_assert_same(['8.8.8.8', '1.1.1.1', '192.168.1.1', '9.9.9.9'], $dns);
});

wgce_test('stored settings remain authoritative over every generated suggestion', static function (): void {
    wgce_config_reset(wgce_config_fixture());
    $GLOBALS['wgce_config_backend']['events'] = [];
    $stored = wgce_config_fixture()['tunnels']['item'][0];
    $suggestedContext = [
        'dns_servers' => ['8.8.8.8'],
        'ddns_records' => [['host' => 'different.example.test']],
        'wan_ipv4' => '93.184.216.34',
        'local_networks' => ['10.0.0.0/8'],
    ];

    $values = wgclientexport_settings_for_ui(
        [
            'name' => 'tun_wg9',
            'listen_port' => 60000,
            'addresses' => ['row' => [['address' => '10.99.0.1', 'mask' => '24']]],
        ],
        $suggestedContext,
        $stored
    );

    wgce_assert_same($stored, $values);
    wgce_assert_same([], $GLOBALS['wgce_config_backend']['events']);
    wgce_assert_same([], $GLOBALS['wgce_wireguard_mutations']);
});

wgce_test_run();
